config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('users.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),

] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from .views import (
    StudentDashboardView, StudentGroupView, StudentLessonsView, 
    HomeworkView, HomeDetailView, ProfileView, EditProfileView, 
    ResetPasswordView,HomeworkListView,student_total_oylik
)

app_name = 'students'
urlpatterns = [
    path('dashboard/', StudentDashboardView.as_view(), name='dashboard'),
    path('groups/', StudentGroupView.as_view(), name='groups'),
    path('resed_password/', ResetPasswordView.as_view(), name='resed_password'),
    path('profil-students/', ProfileView.as_view(), name='profil'),
    path('lessons/<int:group_id>/', StudentLessonsView.as_view(), name='lessons'),
    path('homework/<int:lesson_id>/', HomeworkView.as_view(), name='homework'),
    path('edit/<int:id>/', EditProfileView.as_view(), name='edit'),
    path('homework-detail/<int:lesson_id>/', HomeDetailView.as_view(), name='homework_detail'),
    path('homeworks/<int:lesson_id>/', HomeworkListView.as_view(), name='homework_list'),
    path('student/<int:student_id>/payments/', student_total_oylik, name='student_total_oylik'),
  ]

teachers/urls.py
from django.urls import path
from .views import  (TeacherView,TeacherTimesView,TeacherGroup,TeacherHomeworks,CreateMonthView,TolovListView,DeleteStudent,
                     TeacherStudentsView,ProfileView,EditProfileView,ResetPasswordView,DeleteMonthView,CreateTolovView,
                     TeacherCreateLessonView,TeacherStudentLeson,DavomatListView,TeacherMonthStudent,TeamStudentListView,
                     DateCreateView,StudentsDateView,zip_homework_files)
from .views import present_students,create_attendance
app_name = 'teachers'


urlpatterns = [
    path('dashboard/',TeacherView.as_view(),name='dashboard'),
    path('guruhlarim/',TeacherTimesView.as_view(),name='guruhlarim'),
    path('resed_password/',ResetPasswordView.as_view(),name='resed_password'),
    path('profil-teacher/',ProfileView.as_view(),name='profil'),
    path('guruh/<int:team_id>/',TeacherGroup.as_view(),name='guruh'),
    path('homework/<int:team_id>/',TeacherHomeworks.as_view(),name='homeworks'),
    path('edit/<int:id>/',EditProfileView.as_view(),name='edit'),
    path('student/<int:team_id>/',TeacherStudentsView.as_view(),name='student'),
    path('create/<int:team_id>/',TeacherCreateLessonView.as_view(),name='create'),
    path('stydents/<int:id>/',TeacherStudentLeson.as_view(),name='stydents'),
    path('davomat/<int:id>/', DavomatListView.as_view(), name='davomat_list'),
    path('month/<int:id>/', TeacherMonthStudent.as_view(), name='month_student'),
    path('create-month/<int:team_id>/', CreateMonthView.as_view(), name='createmont'),
    path('delete-month/<int:id>', DeleteMonthView.as_view(), name='deletemont'),
    path('create-tolov/<int:month_id>/', CreateTolovView.as_view(), name='create_tolov'),
    path('tolov-list/<int:id>/', TolovListView.as_view(), name='tolov_list'),
    path('delete-student-list/<int:id>/', DeleteStudent.as_view(), name='delete_student'),
    path('team/student/create/', TeamStudentListView.as_view(), name='create_student'),
    path('create-date/<int:team_id>/', DateCreateView.as_view(), name='create_date'),
    path('teachers/date-list/<int:team_id>/', StudentsDateView.as_view(), name='students_date_list'),
    path('present-students/<int:date_id>/', present_students, name='present_students'),
    path('create-attendance/<int:date_id>/', create_attendance, name='create_attendance'),
     path('zip_homework_files/<int:student_id>/', zip_homework_files, name='zip_homework_files'),
]

users/urls.py
from django.urls import path
from .views import (LoginView, RegisterView,ProfileView,EditProfileView,Create,TeamStudentListView,TolovGroupsView,
                    LogautView,GroupsView,StudentView,EditStudentView,Delete,StudentByTeam,TeacherView,TeacherAdminMonthStudent,
                    ResetPasswordView,AdminDashboardView,CreateTeamView,DeleteTeamView,DeleteTeacher,TolovTeacherListView)

app_name = 'users'


urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogautView.as_view(), name='logout'),
    path('create/', Create.as_view(), name='create'),
    path('profil/', ProfileView.as_view(), name='profil'),
    path('dashboard/', AdminDashboardView.as_view(), name='dashboard'),
    path('edit/<int:id>/', EditProfileView.as_view(), name='edit'),
    path('group/', GroupsView.as_view(), name='groups'),
    path('students/', StudentView.as_view(), name='students'),
    path('get-by-students/<int:id>/', StudentByTeam.as_view(), name='students_by'),
    path('edit-student/<int:id>/', EditStudentView.as_view(), name='edit_student'),
    path('delete/<int:id>/', Delete.as_view(), name='delete'),
    path('resed-password', ResetPasswordView.as_view(), name='resed_password'),
    path('create-team/', CreateTeamView.as_view(), name='create_team'),
    path('teacher/', TeacherView.as_view(), name='teacher'),
    path('teacher-tolov/', TolovGroupsView.as_view(), name='teacher_tolov'),
    path('delete-team/<int:id>/', DeleteTeamView.as_view(), name='delete_team'),
    path('delete-teacher/<int:id>/', DeleteTeacher.as_view(), name='delete_teacher'),
    path('month-teacher/<int:id>/', TeacherAdminMonthStudent.as_view(), name='month_teacher'),
    path('team/student/create/', TeamStudentListView.as_view(), name='create_student'),
    path('tolov-teacher/<int:id>/', TolovTeacherListView.as_view(), name='tolov_teacher'),
]

students/models.py
from django.db import models
from users.models import Team,Student,Teacher
from django.core.validators import MaxValueValidator,FileExtensionValidator

class Lesson(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='lesson')
    title = models.CharField(max_length=100, unique=True)
    date = models.DateField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    homework_status = models.BooleanField(default=False)
    lesson_file = models.FileField(upload_to='lesson/',  null=True,blank=True)
    video = models.FileField(
        upload_to='video/', 
        validators=[FileExtensionValidator(allowed_extensions=['mp4', 'mp3', 'AVI', 'WMV'])],
        null=True,
        blank=True
    )


    class Meta:
        unique_together = ['team', 'title']

    def __str__(self):
        return self.title


class Homework(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name='homework')
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True, related_name='homeworks')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='students')
    description = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['student', 'team']

    def __str__(self):
        return f"{self.student.user.first_name}-- {self.lesson.title}"

class Homework_file(models.Model):
    homework = models.ForeignKey(Homework,on_delete=models.CASCADE, related_name='files')
    homework_file = models.FileField(upload_to='homeworks', blank=True, null=True)





class Date(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    team = models.ForeignKey(Team,on_delete=models.CASCADE,related_name='team',null=True,blank=True)

    def __str__(self):
        return str(self.date)

class Davomat(models.Model):
    team = models.ForeignKey(Team,on_delete=models.CASCADE,related_name='teamsa',null=True,blank=True)
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    date = models.ForeignKey(Date,on_delete=models.CASCADE)
    status = models.BooleanField(default=True)

    def __str__(self) -> str:
        return f"{self.student.user.first_name}"

teachers/models.py
from django.db import models
from users.models import Student, Team
from django.db.models import Sum

class Month(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='tolov_set')
    month = models.CharField(max_length=150)

    def __str__(self) -> str:
        return f"{self.month} "

class Tolov(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='tolovs')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='tolov_sets')
    month = models.ForeignKey(Month, on_delete=models.CASCADE, related_name="tolov_set")
    oylik = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.student.user.first_name} --> {self.student.user.last_name} ({self.oylik})"

    @classmethod
    def total_oylik_for_month(cls, month_id):
        return cls.objects.filter(month_id=month_id).aggregate(total_oylik=Sum('oylik'))['total_oylik'] or 0

students/forms.py
from django import forms
from .models import Homework,Davomat,Homework_file

class HomeworkForm(forms.Form):
    description = forms.CharField(widget=forms.TextInput({'class': 'form-control'}))



class HomeworkFileForm(forms.ModelForm):
    class Meta:
        model = Homework_file
        fields = ['homework_file']


class DavomatForm(forms.ModelForm):
    class Meta:
        model = Davomat
        fields = [ 'student', 'status'] 
        widgets = {
            'team': forms.Select(attrs={'class': 'form-control'}),
            'student': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

teachers/forms.py
from django import forms
from students.models import Davomat ,Lesson,Date
from .models import Month, Tolov
from users.models import User

class TeacherProfileForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Name"}))
    phone_number = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Phone Number"}))
    first_name = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "First Name"}))
    last_name = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Last Name"}))
    jobs = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Jobs"}))
    address = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "address"}))
    email = forms.CharField(widget=forms.EmailInput({"class": "form-control", "placeholder": "address"}))
    image = forms.ImageField(widget=forms.FileInput({"class": "form-control", "placeholder": "image"}))
    
    class Meta:
        model = User
        fields = ('username', 'phone_number','address', 'first_name', 'last_name','image','email','jobs')

class MonthForm(forms.ModelForm):
    class Meta:
        model = Month
        fields = [ 'month']
        widgets = {
            'month': forms.TextInput(attrs={'placeholder': 'Enter month name'}),
        }

class TolovForm(forms.ModelForm):
    class Meta:
        model = Tolov
        fields = ['student',  'oylik']
        widgets = {
            'oylik': forms.NumberInput(attrs={'placeholder': 'Enter the amount'}),
        }


class CreateLessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = [ 'title', 'homework_status', 'lesson_file']
    
    title = forms.CharField(widget=forms.TextInput({'class': 'form-control'}))


class DavomatForm(forms.ModelForm):
    class Meta:
        model = Davomat
        fields = [ 'student', 'status','date'] 
        widgets = {
            'student': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

class DateForm(forms.ModelForm):
    class Meta:
        model = Date
        fields = '__all__' 

students/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from users.permissionmixin import StudentRequiredMixin
from django.views import View
from users.models import Student, Team,User
from .forms import HomeworkForm,DavomatForm
from .models import Lesson, Homework,Davomat,Homework_file
from users.forms import ProfileForm,ResetPasswordForm

class StudentDashboardView(StudentRequiredMixin, View):
    def get(self, request):
        return render(request, 'students/dashboard.html')

class StudentGroupView(StudentRequiredMixin, View):
    def get(self, request):
        student = Student.objects.get(user=request.user)
        return render(request, 'students/guruhlarim.html', context={"student":student})
    
class HomeworkListView(View):
    def get(self, request, lesson_id):
        lesson = get_object_or_404(Lesson, id=lesson_id)
        homeworks = Homework.objects.filter(lesson=lesson)
        return render(request, 'students/homework.html', {'lesson': lesson, 'homeworks': homeworks})

class StudentLessonsView(StudentRequiredMixin, View):
    def get(self, request, group_id):
        team = get_object_or_404(Team, id=group_id)
        lessons = team.lesson.all()
        return render(request, 'students/lessons.html', context={"lessons":lessons})
    
class HomeworkView(StudentRequiredMixin, View):
    def get(self, request, lesson_id):
        form = HomeworkForm()  # Form for description
        return render(request, 'students/homework.html', context={"form": form})

    def post(self, request, lesson_id):
        lesson = get_object_or_404(Lesson, id=lesson_id)
        student = get_object_or_404(Student, user=request.user)

        form = HomeworkForm(request.POST)
        files = request.FILES.getlist('homework_file')  # Get the list of uploaded files

        if form.is_valid():
            # Create Homework object
            homework = Homework.objects.create(
                lesson=lesson,
                student=student,
                description=form.cleaned_data['description']
            )

            # Handle the file uploads
            for file in files:
                Homework_file.objects.create(homework=homework, homework_file=file)

            # Update lesson status
            lesson.homework_status = True
            lesson.save()

            return redirect('students:dashboard')

        return render(request, 'students/homework.html', context={"form": form})


        
class HomeDetailView(StudentRequiredMixin,View):
    def get(self,request,lesson_id):
        lesson = get_object_or_404(Lesson,id=lesson_id)
        student = get_object_or_404(Student , user=request.user)
        homework = Homework.objects.filter(lesson=lesson , student=student).first()
        return render(request,'students/homedetail.html',{'homework':homework})
    
class ProfileView(LoginRequiredMixin,View):
    def get(self,request):
        user = request.user
        return render(request,'students/profil.html',context={"user":user})


class EditProfileView(LoginRequiredMixin, View):
    def get(self, request, id):
        user = get_object_or_404(User, id=id)
        form = ProfileForm(instance=user)
        return render(request, 'students/edit.html', {'form': form})

    def post(self, request, id):
        user = get_object_or_404(User, id=id)
        form = ProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('students:profil')  
        return render(request, 'students/edit.html', {'form': form})

class ResetPasswordView(LoginRequiredMixin,View):
    def get(self, request):
        form = ResetPasswordForm()
        return render(request, 'students/reset_password.html', {'form':form})

    def post(self, request):
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data['new_password']
            user = request.user
            user.set_password(new_password)
            user.save()
            return redirect('/')
        form = ResetPasswordForm()
        return render(request, 'students/reset_password.html', {'form':form})
    
class DavomatListView(View):
    def get(self, request):
        davomat_list = Davomat.objects.all()
        form = DavomatForm()
        return render(request, 'students/davomat_list.html', {'davomat_list': davomat_list, 'form': form})

    def post(self, request):
        form = DavomatForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('davomat_list')
        davomat_list = Davomat.objects.all()
        return render(request, 'students/davomat_list.html', {'davomat_list': davomat_list, 'form': form})

def student_total_oylik(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    total_oylik = Tolov.total_oylik_for_student(student_id)  
    tolovlar = Tolov.objects.filter(student=student)
    
    context = {
        'student': student,
        'total_oylik': total_oylik,
        'tolovlar': tolovlar,
    }
    return render(request, 'students/student_oylik.html', context)


    

users/templates/users/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>IT academy</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'icon/talim.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-fluid position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-light navbar-light">
                <a href="#" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-success">Ummat Ta'lim</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="{{user.image.url}}" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">{{user.first_name}}</h6>
                        <span>{{user.user_role}}</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">

                    </div>
                    <a href="{% url 'users:groups' %}" class="nav-item nav-link"><i class="fas fa-users fa-fw me-4"></i>Guruhlar</a>
                    <a href="{% url 'users:teacher' %}" class="nav-item nav-link"><i class="fas fa-users fa-fw me-4"></i>Ustozlar</a>
                    <a href="{% url 'users:teacher_tolov' %}" class="nav-item nav-link"><i class="fas fa-money-bill fa-fw me-3"></i>To'lovlar</a>
                    <a href="{% url 'users:profil' %}" class="nav-item nav-link"><i class="fas fa-chart-bar fa-fw me-3"></i>Sozlamalar</a>
                    <a href="{% url 'users:register' %}" class="nav-item nav-link"><i class="fas fa-chart-bar fa-fw me-3"></i>Register</a>
                    <a href="{% url 'users:create_student' %}" class="nav-item nav-link"><i class="fas fa-chart-bar fa-fw me-3"></i>Student Register</a>

                </div>
            </nav>
        </div>
        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
        <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
            <a href="#" class="navbar-brand d-flex d-lg-none me-4">
                <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
            </a>
            <a href="#" class="sidebar-toggler flex-shrink-0">
                <i class="fa fa-bars"></i>
            </a>
            <form class="d-none d-md-flex ms-4">
                <input class="form-control border-0" type="search" placeholder="Search">
            </form>
            <div class="navbar-nav align-items-center ms-auto">
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                        <img class="rounded-circle me-lg-2" src="{{ user.image.url }}" alt="" style="width: 40px; height: 40px;">
                        <span class="d-none d-lg-inline-flex">{{ user.first_name }}</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                        <a href="{% url 'users:profil' %}" class="dropdown-item">My Profile</a>
                        <a href="{% url 'users:logout' %}" class="dropdown-item">Log Out</a>
                    </div>
                </div>
            </div>
            <!-- Navbar Start -->
            
            </nav>
            <!-- Navbar End -->
        {% block content %}

        {% endblock content %}

        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

users/templates/users/groups.html
{% extends 'users/dashboard.html' %}

{% block content %}
<div class="container">
<table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
      <tr>
        <th>Title</th>
        <th>Status</th>
        <th>Name</th>
        <th>Actions</th>
        <th><a class="btn btn-outline-success" href="{% url 'users:create_team'  %}">create</a></th>

      </tr>
    </thead>
    <tbody>
    {% for i in teams %}
      <tr>
        <td>
          <p class="fw-normal mb-1">{{i.name}}</p>
        </td>
        <td>
          <span class="badge badge-success rounded-pill d-inline">Active</span>
        </td>
        <td>
          <p class="fw-normal mb-1">{{i.teacher.user.first_name}}</p>
        </td>
        
        <td>
          <a class="btn btn-outline-info" href="{% url 'users:students_by' i.id %}">Show</a>
        </td> 
<!-- Delete Confirmation Modal -->
<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-sm"> <!-- Use modal-sm for smaller size -->
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Ochirishni xohlaysizmi?</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            {{i.name}}
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Yo'q</button>
              <a id="confirmDeleteBtn" href="#" class="btn btn-danger">Ha</a>
          </div>
      </div>
  </div>
</div>

<!-- Your table and button code -->
<td>
    <button type="button"  class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal" data-url="{% url 'users:delete_team' i.id %}">
      <i class="fas fa-trash-alt"></i>
    </button>
</td>

<!-- Bootstrap JS (Ensure it's included) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<script>
  // Attach URL to the "Ha" button dynamically when the modal is shown
  const deleteModal = document.getElementById('deleteModal');
  deleteModal.addEventListener('show.bs.modal', function (event) {
      const button = event.relatedTarget; // Button that triggered the modal
      const url = button.getAttribute('data-url'); // Extract URL from data-url attribute
      const confirmDeleteBtn = deleteModal.querySelector('#confirmDeleteBtn');
      confirmDeleteBtn.setAttribute('href', url); // Set the URL to the "Ha" button
  });
</script>

<!-- Custom CSS for positioning modal at the top and removing backdrop -->
<style>
  .modal-dialog {
      margin-top: 5vh; /* Adjust the margin to move the modal closer to the top */
  }
  @media (max-width: 576px) {
      .modal-dialog {
          margin-top: 3vh; /* Adjust for smaller screens */
      }
  }
  .modal-backdrop {
      display: none; /* Remove the black backdrop */
  }
</style>






      </tr>
    {% endfor %}

    </tbody>
  </table>
</div>
{% endblock content %}

users/templates/users/table.html
{% extends 'users/dashboard.html' %}

{% block content %}
<div class="container">
<a href="{% url 'users:create' %}" class="btn btn-outline-success ms-1">creat</a>

<table class="table table-primary">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">First name</th>
        <th scope="col">last name</th>
        <th scope="col">phone number</th>
        <th scope="col"> address</th>
        <th scope="col"> email</th>
        <th scope="col">Name</th>
        {% if user.is_authenticated %}
        <th scope="col">Button</th>
        {% endif %}
      </tr>
    </thead>
    {% for i in form %}
    <tbody>
      <tr>
        <th scope="row">{{i.id}}</th>
        {% if request.user.is_authenticated %}
        <td><a href="{% url 'users:profil' i.id %}">{{i.first_name}}</a></td>
        {% else %}
        <td>{{i.first_name}}</td>
        {% endif %}
        <td>{{i.last_name}}</td>
        <td>{{i.phone_number}}</td>
        <td>{{i.address}}</td>
        <td>{{i.email}}</td>
        <td>{{i.username}}</td>
        <td>
          {% if user.is_authenticated %}
          <a class="btn btn-outline-danger" href="{% url 'users:delete' i.id %}">Delete</a>
          <a class="btn btn-outline-info" href="{% url 'users:edit' i.id %}">Edit</a>
          {% endif %}
        </td>
      </tr>
      
    </tbody>
    {% endfor %}
  </table>
</div>
{% endblock content %}